### PR TITLE
Add gopath to gitignore

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Add gopath to gitignore (created when using `make dep`)

**Special notes for your reviewer**:
once merged need to cherry-pick also to
release-0.31 | release-0.29 | release-0.26

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by phoracek** [comment]
OVS CNI has a user base outside CNAO. It is not justified to change its development tooling to be in sync with another project.

If you drop the target change and keep the gitignore modification, I will be happy to merge this.

**Comment by oshoval** [comment]
Sure thx
is it fine btw to add another target and not replace ? (can be done also on follow PR if so)

**Comment by oshoval** [comment]
Updated

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Comment by phoracek** [comment]
I would rather not add a target to make it slightly more convenient for other projects. Sorry for the complication.

**Comment by oshoval** [comment]
Np
btw if you want to consider an alias instead of a new target, anyhow not biggie
`vendor: dep`

**Pull request merged**
