### PR TITLE
Bump CNI plugin to 1.0.1

### PR DESCRIPTION
**Pull request by masap**
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

### CODE REVIEW

**Comment by masap** [comment]
Re run LGTM analysis: C/C++ after #207 is merged.

**Comment by masap** [comment]
Could anybody re-run ```LGTM analysis: C/C++``` ?

**Comment by phoracek** [comment]
/lgtm
/approve

Ignoring LGTM as it is irrelevant and fights with the rebase.

**Comment by masap** [comment]
> Ignoring LGTM as it is irrelevant and fights with the rebase.

Ok, thanks.

**Pull request merged**
