### PR TITLE
[release-0.19] resources, Update minimum resources request

### PR DESCRIPTION
**Pull request by oshoval**
cherry-pick of https://github.com/k8snetworkplumbingwg/ovs-cni/pull/177

Update ovs-cni resources requests according to empiric use cases.

See https://bugzilla.redhat.com/show_bug.cgi?id=1935218

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/k8snetworkplumbingwg_ovs-cni/182/pull-e2e-ovs-cni-0.19/1414987774859153408

I think its not due to the PR, but need 2nd opinion and to check little more, lets start by few reruns

/retest

**Comment by oshoval** [comment]
the error is not due to this PR, 
it happens on vanilla release-0.19

PR that fixes it
https://github.com/k8snetworkplumbingwg/ovs-cni/pull/185

**Comment by oshoval** [comment]
/hold cancel

but should be merged only after the problem above is fixed

**Comment by oshoval** [comment]
```
daemonset.apps/kube-multus-ds-s390x created
+ ./cluster/kubectl.sh -n kube-system wait --for=condition=ready -l name=multus pod --timeout=300s
error: no matching resources found
make: *** [Makefile:83: cluster-up] Error 1
```
Weird first time i see it, 
will check tomorrow, maybe worth to move to k8s-1.19 as CNAO

Thanks

**Comment by oshoval** [comment]
Just rebased, trying to run again to see if frequency

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/k8snetworkplumbingwg_ovs-cni/182/pull-e2e-ovs-cni-0.19/1415338668029120512
passed

lets just run again another time
/test pull-e2e-ovs-cni-0.19

**Comment by oshoval** [comment]
passed

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Comment by oshoval** [comment]
Thanks
can you please create a release ?

**Pull request merged**
