### PR TITLE
Bump openvswitch to 2.15

### PR DESCRIPTION
**Pull request by masap**
Bump openvswitch version and Fedora version for integration tests.

release-note
```release-note
Bump openvswitch to 2.15
Bump Fedora to 34
```

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

### CODE REVIEW

**Comment by phoracek** [comment]
/ok-to-test

Thanks @masap, this was long overdue.

**Comment by masap** [comment]
```sudo automation/check-patch.e2e.sh``` command works in my environment.
To run the same test as ```pull-e2e-ovs-cni```, what command should I run ?

**Comment by phoracek** [comment]
/retest

Oddly, it fails on system setup phase due to unavailable Golang ... probably a transient issue.

```
 ---> Running in 33734afa9688
[91mUnable to setup go bootstrap from existing or binary
[0m[91mI don't have any idea what to do with '1.16'.
  (using download type 'auto')
[0mThe command '/bin/sh -c mkdir -p /gimme && curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | HOME=/gimme bash >> /etc/profile.d/gimme.sh' returned a non-zero code: 1
```

**Comment by phoracek** [comment]
Strange, `make docker-test` works for me locally too. And it is completely containerized, so there should be no difference when it runs on CI. I will investigate it further.

**Comment by masap** [comment]
Rebase and update openvswitch rpm to latest.

**Comment by masap** [comment]
Downgrade Fedora to 33.

**Comment by masap** [comment]
Odd... ```make docker-test``` works with Fedora 33 on my local.

**Comment by masap** [comment]
Back to Fedora 34.

**Comment by phoracek** [comment]
@masap I cannot point to the specific issue, but I got around the problem by replacing Gimme with direct download from Go website. Would you please review https://github.com/k8snetworkplumbingwg/ovs-cni/pull/200? With that, this patch should be passing.

**Comment by masap** [comment]
Thanks !

**Comment by masap** [comment]
@phoracek Great insight !

**Pull request merged**
