### PR TITLE
multus, Update multus manifest

### PR DESCRIPTION
**Pull request by RamLavi**
the multus manifest has gone through some changes[0].
Updated the manifest in order to stay up to date.

[0] k8snetworkplumbingwg/multus-cni#627

### CODE REVIEW

**Comment by RamLavi** [comment]
/retest
looks like quay hiccup

**Comment by RamLavi** [comment]
looks like `make docker-test` is failing.
locally I don't see an issue.
let's wait and see if the issue is nontransient

**Review by phoracek — CHANGES_REQUESTED** [review]
Would you please expand the commit message? Why such a big change, where does it come from.

**Comment by RamLavi** [comment]
> Would you please expand the commit message? Why such a big change, where does it come from.

updated the commit message.
The changes relevant to us are mainly the DaemonSet name `kube-multus-ds` and the image url `ghcr.io/k8snetworkplumbingwg/multus-cni:stable`.
I initially thought that the old image `docker.io/nfvpe/multus:stable` is not available, which is what triggered this PR, but it was only a temporary thing..

So we can still bump to keep things up to date, but it's not as important as I initially thought. what do you think @phoracek ?

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

I don't mind bumping. It may make future bumps (that would be mandatory) easier.

**Pull request merged**
