### PR TITLE
travis, Remove travis script

### PR DESCRIPTION
**Pull request by RamLavi**
As travis org will be soon deprecated, we want to move our
post-submits to project infra[0].

[0] kubevirt/project-infra#1352

### CODE REVIEW

**Comment by RamLavi** [comment]
/hold

we will use this PR merging to check this [PR](https://github.com/kubevirt/project-infra/pull/1352) once merged.

**Review by oshoval — APPROVED** [review]

**Comment by oshoval** [comment]
/lgtm

dont think i have permissions

**Comment by RamLavi** [comment]
/retest
checking locally I don't see why the `./cluster/kubectl.sh -n kube-system wait --for=condition=ready -l name=multus pod --timeout=300s` failed.

**Comment by RamLavi** [comment]
/hols cancel
project-infra PR merged

**Pull request merged**
