### PR TITLE
Bump Go to 1.17.7

### PR DESCRIPTION
**Pull request by masap**
Because `kubernetes` 1.23 is built with `Go` 1.17.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

Bump `Kubernetes` version of autotest

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

release-note
```release-note
Bump Go version to 1.17.7
```

### CODE REVIEW

**Comment by phoracek** [comment]
@masap thanks for submitting this. The error seems to be related to our CI setup. I will check with my team on what should be our next steps here. Maybe we have to tweak the CI, maybe move this project to Podman instead.

**Comment by masap** [comment]
Ok, thanks !

**Pull request merged**
