### PR TITLE
Add support for CHECK command

### PR DESCRIPTION
**Pull request by masap**
Also bump ovs-cni version to 0.4.0.

release-note
```release-note
Add support for CHECK command
Bump ovs-cni version to 0.4.0
```

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

### CODE REVIEW

**Comment by phoracek** [comment]
/cc @pperiyasamy

If you want to take a look. This PR makes it little clearer which CNI versions are supported

**Comment by phoracek** [comment]
@pperiyasamy does it look fine to you now?

**Review by pperiyasamy — APPROVED** [review]

**Comment by pperiyasamy** [comment]
> @pperiyasamy does it look fine to you now?

@phoracek it looks good to me. Thanks @masap .

**Comment by phoracek** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
