### PR TITLE
Rename all imports to refer to npwg

### LINKED ISSUE #152: Rename all imports so they use the new organization
After migration from kubevirt GitHub org, all the imports are still pointing to the old org.

### PR DESCRIPTION
**Pull request by phoracek**
The project was migrated from kubevirt GitHub org under
k8snetworkplumbingwg, hence renaming all import references. Follow-up
patches should address resource naming and image registry.

Fixes #152

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
/approve
/hold

Looks good, feel free to unhold when ready.

**Comment by fgimenez** [comment]
/lgtm

(not sure if i can approve though :))

**Comment by rhrazdil** [comment]
The code change looks good to me.
The description points to a PR 155, while I think want to point to this issue https://github.com/k8snetworkplumbingwg/ovs-cni/issues/152

/lgtm

**Comment by phoracek** [comment]
Thanks all, fixed the description.

/approve

**Pull request merged**
