### PR TITLE
[release-0.29] chore: Update golang.org/x/* modules

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Updated modules golang.org/x/* to the latest versions.

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
Waiting for https://github.com/k8snetworkplumbingwg/ovs-cni/pull/288

**Comment by oshoval** [comment]
> Waiting for #288

merged

**Pull request merged**
