### PR TITLE
Bump go to 1.22.9

### PR DESCRIPTION
**Pull request by phoracek**
**What this PR does / why we need it**:

This is to address a CVE, reported in #331.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by smoshiur1237** [comment]
Thanks @phoracek  for this uplift. would you please update the docker file go version in the following line to 1.22.7?
https://github.com/k8snetworkplumbingwg/ovs-cni/blob/9f9bb719fd2bd9e51aa05408eaf9781bd59d3c0e/hack/docker-builder/Dockerfile#L9

**Comment by smoshiur1237** [comment]
I have the understanding that go mod file change should have minimum go version that it supports. As earlier version of 1.22.7 has the vulnerability, isn't it better to update the go version to 1.22.7 in `go mod` file and same in docker file ( `ovs-cni/hack/docker-builder/Dockerfile` ).

**Comment by phoracek** [comment]
@smoshiur1237 the Go version in the docker-builder should be only relevant to the Go used in test runs. But it's a good catch - I should update it too.

The version that matters for our containerized distribution is set here https://github.com/k8snetworkplumbingwg/ovs-cni/blob/main/cmd/Dockerfile#L10, and it is based on the one listed in Go.mod. Binary builds attached to releases are currently built by me manually (no CI), but they should follow the Go.mod directive.

**Comment by smoshiur1237** [comment]
@phoracek  I can understand the go version is taken from go mod file. Is there any issue to use 1.22.7 ?

**Comment by phoracek** [comment]
@smoshiur1237 yes, following semver, if the fix is available in 1.22.7, it should be a part of all the newer z-stream releases.

**Pull request merged**
